/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package vista.admin.averia;

import com.formdev.flatlaf.extras.FlatSVGIcon;
import utils.PanelImgFondo;

import javax.swing.*;
import java.awt.*;

/**
 *
 * @author Thanya
 */
public class TipoAveriaNueva extends javax.swing.JDialog {

    private final controlador.TipoAveriaControlador controlador = new controlador.TipoAveriaControlador();
    private javax.swing.table.DefaultTableModel modeloTabla;

    /**
     * Creates new form TipoAveriaNueva
     */
    public TipoAveriaNueva(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        inicializarSpinnerNumeroTipo();
        mostrarImagenes();        
    }

    /**
     * mostrarImagenes(). Metodo encargado de aplicar los ajustes visuales de la
     * ventana.
     *
     * En este metodo se configuran los elementos graficos comunes de la
     * interfaz, como el icono del JFrame, el tamaño fijo de la ventana, su
     * posicion en pantalla y la desactivacion del redimensionado.
     *
     * Tambien se cargan y asignan los iconos SVG utilizados en la interfaz,
     * como el logo de la aplicacion o los iconos de usuario. Ademas se ajustan
     * propiedades visuales de los componentes Swing (labels, textfields, etc.)
     * para mantener un diseño uniforme en todas las pantallas de la aplicacion.
     */
    public void mostrarImagenes() {
        //Ajustes del deisño del JFrame/Layout
        Image icono = new ImageIcon(getClass().getResource("/recursos/isotipo.png")).getImage();
        this.setIconImage(icono);

        //ide Nuevo txtIdNuevo
        FlatSVGIcon iconoCodigo = new FlatSVGIcon("recursos/iconos/icnNumerico.svg", 16, 16);
        txtIdNuevo.putClientProperty("JTextField.leadingIcon", iconoCodigo);
        txtIdNuevo.putClientProperty("JComponent.padding", new Insets(5, 8, 5, 8));
        txtIdNuevo.putClientProperty("JTextField.placeholderText", "Código Rol:  4 ");
        txtIdNuevo.setEditable(false);
        txtIdNuevo.setEnabled(false);
        // tiempo 
        FlatSVGIcon iconoTime = new FlatSVGIcon("recursos/iconos/temporizador.svg", 16, 16);
        txtTiempoNuevo.putClientProperty("JTextField.leadingIcon", iconoTime);
        txtTiempoNuevo.putClientProperty("JComponent.padding", new Insets(5, 8, 5, 8));
        txtTiempoNuevo.putClientProperty("JTextField.placeholderText", "tiempo estimado en reparar (en horas):  ");
        //Descrpcion
        FlatSVGIcon iconoDescripcion = new FlatSVGIcon("recursos/iconos/icnEtiqueta.svg", 16, 16);
        txtDescripcionTipoAveria.putClientProperty("JTextField.leadingIcon", iconoDescripcion);
        txtDescripcionTipoAveria.putClientProperty("JComponent.padding", new Insets(5, 8, 5, 8));
        txtDescripcionTipoAveria.putClientProperty("JTextField.placeholderText", "Descripción ");
    }

    /**
     * Aquí hemos hecho que el spinner empiece en 1, tenga como mínimo 1, como
     * máximo 99 y avance de uno en uno. Después le ponemos el formato "00" para
     * que visualmente se vea 01, 02, 03... hasta 99.
     */
    private void inicializarSpinnerNumeroTipo() {
        SpinnerNumberModel modeloNumeroRol = new SpinnerNumberModel(1, 1, 99, 1);
        spnNumeroTipo.setModel(modeloNumeroRol);

        JSpinner.NumberEditor editorNumeroRol = new JSpinner.NumberEditor(spnNumeroTipo, "00");
        spnNumeroTipo.setEditor(editorNumeroRol);
    }

    private String obtenerNumeroTipoFormateado() {
        int numeroRol = (int) spnNumeroTipo.getValue();
        String numeroRolFormateado = String.format("%02d", numeroRol);
        return numeroRolFormateado;
    }

    private String obtenerCodigoTipoCompleto() {
        String numeroRolFormateado = obtenerNumeroTipoFormateado();
        String codigoRolCompleto = "4" + numeroRolFormateado;
        return codigoRolCompleto;
    }
    private void cargarDatos() {
        modeloTabla.setRowCount(0);
        java.util.List<Object[]> datos = controlador.listarParaTabla();
        if (datos != null) {
            for (Object[] fila : datos) {
                modeloTabla.addRow(fila);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new PanelImgFondo("/recursos/fondoFormularios.png");
        jPanel1 = new javax.swing.JPanel();
        txtTiempoNuevo = new javax.swing.JTextField();
        btnTipoAveriaCrear = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtIdNuevo = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        spnNumeroTipo = new javax.swing.JSpinner();
        txtDescripcionTipoAveria = new javax.swing.JTextField();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel2.setMaximumSize(new java.awt.Dimension(1000, 600));
        jPanel2.setPreferredSize(new java.awt.Dimension(1000, 600));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        txtTiempoNuevo.setBackground(new java.awt.Color(237, 243, 251));

        btnTipoAveriaCrear.setBackground(new java.awt.Color(58, 181, 235));
        btnTipoAveriaCrear.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        btnTipoAveriaCrear.setForeground(new java.awt.Color(255, 255, 255));
        btnTipoAveriaCrear.setText("Crear");
        btnTipoAveriaCrear.setBorderPainted(false);
        btnTipoAveriaCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTipoAveriaCrearActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Microsoft JhengHei", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 102, 204));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Nuevo tipo de avería");

        txtIdNuevo.setBackground(new java.awt.Color(237, 243, 251));

        txtDescripcionTipoAveria.setBackground(new java.awt.Color(237, 243, 251));

        btnCancelar.setBackground(new java.awt.Color(234, 242, 251));
        btnCancelar.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(67, 113, 177));
        btnCancelar.setText("Cancelar");
        btnCancelar.setBorderPainted(false);
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jSeparator1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(119, 119, 119)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnTipoAveriaCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtTiempoNuevo, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(txtIdNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 86, Short.MAX_VALUE)
                        .addComponent(spnNumeroTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtDescripcionTipoAveria, javax.swing.GroupLayout.Alignment.LEADING))
                .addGap(94, 94, 94))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIdNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spnNumeroTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addComponent(txtTiempoNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(txtDescripcionTipoAveria, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTipoAveriaCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(97, 97, 97))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(101, 101, 101))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTipoAveriaCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTipoAveriaCrearActionPerformed
        try {
            // Obtenemos el ID completo desde el spinner
            String numeroTipoFormateado = obtenerNumeroTipoFormateado();
            String textoId = obtenerCodigoTipoCompleto();

            // Validacion para que el ID empiece por 4
            if (!textoId.startsWith("4")) {
                javax.swing.JOptionPane.showMessageDialog(
                        this,
                        "El ID del nuevo tipo de averia debe empezar obligatoriamente por el numero 4.",
                        "ID Invalido",
                        javax.swing.JOptionPane.WARNING_MESSAGE
                );
                return;
            }

            int id = Integer.parseInt(textoId);
            float tiempo = Float.parseFloat(txtTiempoNuevo.getText().trim());
            String desc = txtDescripcionTipoAveria.getText().trim();

            // Llamamos al controlador. Recuerda que este método internamente llama al void del DAO
            boolean exito = controlador.registrar(id, desc, tiempo);

            if (exito) {
                //javax.swing.JOptionPane.showMessageDialog(this, "Tipo de avería creado con éxito.");                
                //cargarDatos(); // Refrescamos la tabla principal
                
                JOptionPane.showMessageDialog(this, "Tipo de avería actualizado con éxito.");
                dispose();
            }

        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "El ID debe ser un número entero y el tiempo un número (ej. 1.5).",
                    "Error de formato", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnTipoAveriaCrearActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        int respuesta = JOptionPane.showConfirmDialog(this, "¿Deseas cancelar la operación? Los cambios no se guardarán.", "Cancelar operación", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
        if (respuesta == JOptionPane.YES_OPTION) {
            dispose();
        }
    }//GEN-LAST:event_btnCancelarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnTipoAveriaCrear;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSpinner spnNumeroTipo;
    private javax.swing.JTextField txtDescripcionTipoAveria;
    private javax.swing.JTextField txtIdNuevo;
    private javax.swing.JTextField txtTiempoNuevo;
    // End of variables declaration//GEN-END:variables
}
