/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package vista.admin.averia;

/**
 *
 * @author yosnavmol
 */
public class TipoAveriaCRUD extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TipoAveriaCRUD.class.getName());

    // 1. Instanciamos nuestro nuevo controlador y el modelo de la tabla
    private final controlador.TipoAveriaControlador controlador = new controlador.TipoAveriaControlador();
    private javax.swing.table.DefaultTableModel modeloTabla;
    
    /**
     * Creates new form TipoAveriaListar
     */
    public TipoAveriaCRUD(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        // Centrar ventana principal
        this.setLocationRelativeTo(parent);
        
        // Configurar el tamaño de las sub-ventanas ocultas para que no salgan enanas
        TipoAveriaNueva.pack();
        TipoAveriaNueva.setLocationRelativeTo(this);
        
        TipoAveriaActualizar.pack();
        TipoAveriaActualizar.setLocationRelativeTo(this);
        
        // Cargar datos
        inicializarTabla();
        cargarDatos();
    }

    private void inicializarTabla() {
        String[] columnas = {"Cód. Tipo", "Descripción", "Tiempo Prom. (Horas)"};
        modeloTabla = new javax.swing.table.DefaultTableModel(null, columnas) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; // Evita que se edite directamente haciendo doble clic
            }
        };
        tablaAveria.setModel(modeloTabla);
    }

    private void cargarDatos() {
        modeloTabla.setRowCount(0);
        java.util.List<Object[]> datos = controlador.listarParaTabla();
        if (datos != null) {
            for (Object[] fila : datos) {
                modeloTabla.addRow(fila);
            }
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TipoAveriaNueva = new javax.swing.JDialog();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtIdNuevo = new javax.swing.JTextField();
        txtTiempoNuevo = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        taDescripcionNuevo = new javax.swing.JTextArea();
        btnTipoAveriaCrear = new javax.swing.JButton();
        TipoAveriaActualizar = new javax.swing.JDialog();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtIdActualizar = new javax.swing.JTextField();
        txtTiempoActualizar = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        taDescripcionActualizar = new javax.swing.JTextArea();
        btnTipoAveriaGuardar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaAveria = new javax.swing.JTable();
        btnTipoAveriaNuevo = new javax.swing.JButton();
        btnTipoAveriaEliminar = new javax.swing.JButton();
        btnTipoAveriaActualizar = new javax.swing.JButton();

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Nuevo tipo de avería");

        jLabel1.setText("ID (debe empezar por 4):");

        jLabel4.setText("Descripción:");

        jLabel5.setText("Tiempo estimado en reparar (en horas):");

        taDescripcionNuevo.setColumns(20);
        taDescripcionNuevo.setRows(5);
        jScrollPane2.setViewportView(taDescripcionNuevo);

        btnTipoAveriaCrear.setText("Crear");
        btnTipoAveriaCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTipoAveriaCrearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout TipoAveriaNuevaLayout = new javax.swing.GroupLayout(TipoAveriaNueva.getContentPane());
        TipoAveriaNueva.getContentPane().setLayout(TipoAveriaNuevaLayout);
        TipoAveriaNuevaLayout.setHorizontalGroup(
            TipoAveriaNuevaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(TipoAveriaNuevaLayout.createSequentialGroup()
                .addGroup(TipoAveriaNuevaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(TipoAveriaNuevaLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(TipoAveriaNuevaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel4)
                            .addGroup(TipoAveriaNuevaLayout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtIdNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(TipoAveriaNuevaLayout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtTiempoNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane2)))
                    .addGroup(TipoAveriaNuevaLayout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addComponent(btnTipoAveriaCrear)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        TipoAveriaNuevaLayout.setVerticalGroup(
            TipoAveriaNuevaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TipoAveriaNuevaLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(TipoAveriaNuevaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtIdNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(TipoAveriaNuevaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtTiempoNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnTipoAveriaCrear)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Actualizar tipo de avería");

        jLabel7.setText("ID de tipo de avería:");

        jLabel8.setText("Tiempo promedio en reparar (horas):");

        jLabel9.setText("Descripción:");

        txtIdActualizar.setEditable(false);

        taDescripcionActualizar.setColumns(20);
        taDescripcionActualizar.setRows(5);
        jScrollPane3.setViewportView(taDescripcionActualizar);

        btnTipoAveriaGuardar.setText("Guardar");
        btnTipoAveriaGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTipoAveriaGuardarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout TipoAveriaActualizarLayout = new javax.swing.GroupLayout(TipoAveriaActualizar.getContentPane());
        TipoAveriaActualizar.getContentPane().setLayout(TipoAveriaActualizarLayout);
        TipoAveriaActualizarLayout.setHorizontalGroup(
            TipoAveriaActualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(TipoAveriaActualizarLayout.createSequentialGroup()
                .addGroup(TipoAveriaActualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(TipoAveriaActualizarLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(TipoAveriaActualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane3)
                            .addGroup(TipoAveriaActualizarLayout.createSequentialGroup()
                                .addGroup(TipoAveriaActualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(TipoAveriaActualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtIdActualizar, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                                    .addComponent(txtTiempoActualizar)))))
                    .addGroup(TipoAveriaActualizarLayout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addComponent(btnTipoAveriaGuardar)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        TipoAveriaActualizarLayout.setVerticalGroup(
            TipoAveriaActualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TipoAveriaActualizarLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addGroup(TipoAveriaActualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtIdActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(TipoAveriaActualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtTiempoActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnTipoAveriaGuardar)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Gestón de tipos de averías");

        tablaAveria.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaAveria);

        btnTipoAveriaNuevo.setText("Nuevo");
        btnTipoAveriaNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTipoAveriaNuevoActionPerformed(evt);
            }
        });

        btnTipoAveriaEliminar.setBackground(new java.awt.Color(255, 153, 153));
        btnTipoAveriaEliminar.setText("Eliminar");
        btnTipoAveriaEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTipoAveriaEliminarActionPerformed(evt);
            }
        });

        btnTipoAveriaActualizar.setText("Actualizar");
        btnTipoAveriaActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTipoAveriaActualizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnTipoAveriaActualizar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnTipoAveriaEliminar))
                    .addComponent(btnTipoAveriaNuevo)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(btnTipoAveriaNuevo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnTipoAveriaActualizar)
                    .addComponent(btnTipoAveriaEliminar))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // =========================================================================
    // EVENTOS DE LOS BOTONES PRINCIPALES
    // =========================================================================
    
    private void btnTipoAveriaEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTipoAveriaEliminarActionPerformed
        // 1. Verificar selección
        int fila = tablaAveria.getSelectedRow();
        if (fila == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, 
                "Selecciona un tipo de avería para eliminar.", 
                "Aviso", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        // 2. Extraer ID y Descripción
        int id = (int) modeloTabla.getValueAt(fila, 0);
        String desc = (String) modeloTabla.getValueAt(fila, 1);

        // 3. Confirmación
        int respuesta = javax.swing.JOptionPane.showConfirmDialog(this, 
            "¿Eliminar el tipo #" + id + ": " + desc + "?\nNo podrás borrarlo si ya se está usando en alguna avería.", 
            "Confirmar", javax.swing.JOptionPane.YES_NO_OPTION, javax.swing.JOptionPane.WARNING_MESSAGE);

        // 4. Procesar eliminación (Llamando al boolean del Controlador)
        if (respuesta == javax.swing.JOptionPane.YES_OPTION) {
            boolean exito = controlador.eliminar(id);
            if (exito) {
                javax.swing.JOptionPane.showMessageDialog(this, "Eliminado con éxito.");
                cargarDatos(); // Recargamos la tabla
            } else {
                javax.swing.JOptionPane.showMessageDialog(this, 
                    "No se puede eliminar porque está en uso por alguna Avería.", 
                    "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnTipoAveriaEliminarActionPerformed

    private void btnTipoAveriaActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTipoAveriaActualizarActionPerformed
        // 1. Verificar selección
        int fila = tablaAveria.getSelectedRow();
        if (fila == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, 
                "Selecciona un tipo de avería de la tabla.", 
                "Aviso", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        // 2. Extraer datos de la tabla seleccionada
        int id = (int) modeloTabla.getValueAt(fila, 0);
        String desc = (String) modeloTabla.getValueAt(fila, 1);
        float tiempo = (float) modeloTabla.getValueAt(fila, 2);

        // 3. Rellenar las cajas de la ventana de actualización
        txtIdActualizar.setText(String.valueOf(id));
        taDescripcionActualizar.setText(desc);
        txtTiempoActualizar.setText(String.valueOf(tiempo));

        // 4. Mostrar la ventana interna
        TipoAveriaActualizar.setModal(true);
        TipoAveriaActualizar.setLocationRelativeTo(this);
        TipoAveriaActualizar.setVisible(true);
    }//GEN-LAST:event_btnTipoAveriaActualizarActionPerformed

    private void btnTipoAveriaNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTipoAveriaNuevoActionPerformed
        // Limpiamos las cajas de texto por si quedaron cosas escritas de antes
        txtIdNuevo.setText("");
        taDescripcionNuevo.setText("");
        txtTiempoNuevo.setText("");
        
        // Mostramos la ventana interna
        TipoAveriaNueva.setModal(true);
        TipoAveriaNueva.setLocationRelativeTo(this);
        TipoAveriaNueva.setVisible(true);
    }//GEN-LAST:event_btnTipoAveriaNuevoActionPerformed

    private void btnTipoAveriaCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTipoAveriaCrearActionPerformed
        try {
            String textoId = txtIdNuevo.getText().trim();
            
            // Validación paraque el ID empiece por 4
            if (!textoId.startsWith("4")) {
                javax.swing.JOptionPane.showMessageDialog(this, 
                    "El ID del nuevo tipo de avería debe empezar obligatoriamente por el número 4.", 
                    "ID Inválido", 
                    javax.swing.JOptionPane.WARNING_MESSAGE);
            }
            
            int id = Integer.parseInt(txtIdNuevo.getText().trim());
            float tiempo = Float.parseFloat(txtTiempoNuevo.getText().trim());
            String desc = taDescripcionNuevo.getText().trim();

            // Llamamos al controlador. Recuerda que este método internamente llama al void del DAO
            boolean exito = controlador.registrar(id, desc, tiempo);
            
            if (exito) {
                javax.swing.JOptionPane.showMessageDialog(this, "Tipo de avería creado con éxito.");
                TipoAveriaNueva.setVisible(false); // Ocultamos la sub-ventana
                cargarDatos(); // Refrescamos la tabla principal
            }
            
        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(this, 
                "El ID debe ser un número entero y el tiempo un número (ej. 1.5).", 
                "Error de formato", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnTipoAveriaCrearActionPerformed

    private void btnTipoAveriaGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTipoAveriaGuardarActionPerformed
        // TODO add your handling code here:
        try {
            // El ID lo sacamos pero no dejamos que lo editen
            int id = Integer.parseInt(txtIdActualizar.getText().trim());
            float tiempo = Float.parseFloat(txtTiempoActualizar.getText().trim());
            String desc = taDescripcionActualizar.getText().trim();

            boolean exito = controlador.actualizar(id, desc, tiempo);
            
            if (exito) {
                javax.swing.JOptionPane.showMessageDialog(this, "Tipo de avería actualizado con éxito.");
                TipoAveriaActualizar.setVisible(false); // Ocultamos la sub-ventana
                cargarDatos(); // Refrescamos la tabla principal
            }
            
        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(this, 
                "El tiempo debe ser un valor numérico (ej. 2.5).", 
                "Error de formato", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnTipoAveriaGuardarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                TipoAveriaCRUD dialog = new TipoAveriaCRUD(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog TipoAveriaActualizar;
    private javax.swing.JDialog TipoAveriaNueva;
    private javax.swing.JButton btnTipoAveriaActualizar;
    private javax.swing.JButton btnTipoAveriaCrear;
    private javax.swing.JButton btnTipoAveriaEliminar;
    private javax.swing.JButton btnTipoAveriaGuardar;
    private javax.swing.JButton btnTipoAveriaNuevo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea taDescripcionActualizar;
    private javax.swing.JTextArea taDescripcionNuevo;
    private javax.swing.JTable tablaAveria;
    private javax.swing.JTextField txtIdActualizar;
    private javax.swing.JTextField txtIdNuevo;
    private javax.swing.JTextField txtTiempoActualizar;
    private javax.swing.JTextField txtTiempoNuevo;
    // End of variables declaration//GEN-END:variables
}
