/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package vista;

import utils.PanelImgFondo;
import com.formdev.flatlaf.extras.FlatSVGIcon;
import config.DataSourceFactory;
import controlador.GestionUsuarioControlador;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Image;
import java.io.InputStream;
import java.net.URL;
import java.sql.Connection;
import java.util.HashMap;
import java.util.Map;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;

/**
 *
 * @author Netri
 */
public class panelInformes extends javax.swing.JDialog {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(panelInformes.class.getName());
    private String tipoInforme;
    private int idParametro;

    public panelInformes(java.awt.Frame parent, boolean modal, String tipoInforme, int idParametro) {
        super(parent, modal);
        initComponents();

        this.tipoInforme = tipoInforme;
        this.idParametro = idParametro;

        mostrarReporte();
        mostrarImagenes();
    }

    public void mostrarImagenes() {
        //Ajustes del deisño del JFrame
        Image icono = new ImageIcon(getClass().getResource("/recursos/isotipo.png")).getImage();
        this.setIconImage(icono);
        // Centrar ventana en pantalla
        this.setLocationRelativeTo(null);
    }

    private void mostrarReporte() {
        Connection conexion = null;

        try {
            InputStream reporte = null;
            Map<String, Object> parametros = new HashMap<>();

            if (tipoInforme.equals("averia")) {
                reporte = getClass().getResourceAsStream("/informeJasper/informe_averia.jasper");
                parametros.put("idAveria", idParametro);

            } else if (tipoInforme.equals("maquinas_estado")) {
                reporte = getClass().getResourceAsStream("/informeJasper/informe_maquinas_estado.jasper");
                parametros.put("idEstado", idParametro);

            } else if (tipoInforme.equals("tecnicos")) {
                reporte = getClass().getResourceAsStream("/informeJasper/informe_rendimiento_tecnico.jasper");

            } else {
                throw new RuntimeException("Tipo de informe no soportado.");
            }

            if (reporte == null) {
                throw new RuntimeException("No se encontro el archivo .jasper del informe.");
            }

            conexion = DataSourceFactory.getConnection();

            JasperPrint print = JasperFillManager.fillReport(reporte, parametros, conexion);

            net.sf.jasperreports.swing.JRViewer viewer = new net.sf.jasperreports.swing.JRViewer(print);

            panelVisor.removeAll();
            panelVisor.setLayout(new java.awt.BorderLayout());
            panelVisor.add(viewer, java.awt.BorderLayout.CENTER);
            panelVisor.revalidate();
            panelVisor.repaint();

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this,
                    "Error generando el reporte: " + e.getMessage(),
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
        } finally {
            try {
                if (conexion != null) {
                    conexion.close();
                }
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new PanelImgFondo("/recursos/fondoFormularios.png");
        panelVisor = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Informes");
        setFocusableWindowState(false);

        panelVisor.setBackground(new java.awt.Color(255, 255, 255));
        panelVisor.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addComponent(panelVisor, javax.swing.GroupLayout.PREFERRED_SIZE, 801, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(101, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(panelVisor, javax.swing.GroupLayout.PREFERRED_SIZE, 518, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel panelVisor;
    // End of variables declaration//GEN-END:variables
}
