/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package vista;

import utils.PanelImgFondo;
import java.awt.Font;
import java.io.File;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Netri
 */
public class TablaInformes extends javax.swing.JDialog {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TablaInformes.class.getName());

    /**
     * Creates new form TablaInformes
     */
    public TablaInformes(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        cargarInformes();
    }

    private void cargarInformes() {

        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("Nombre");
        modelo.addColumn("Tipo");
        modelo.addColumn("Fecha");
        modelo.addColumn("Ruta");

        File carpeta = new File("informesPDFGenerados");

        if (!carpeta.exists()) {
            carpeta.mkdirs();
        }

        File[] archivos = carpeta.listFiles((dir, name) -> name.toLowerCase().endsWith(".pdf"));

        if (archivos != null) {
            for (int i = 0; i < archivos.length; i++) {

                File archivo = archivos[i];

                String nombre = archivo.getName();
                String tipo = obtenerTipoInforme(nombre);
                String fecha = new java.text.SimpleDateFormat("dd/MM/yyyy HH:mm")
                        .format(new java.util.Date(archivo.lastModified()));
                String ruta = archivo.getAbsolutePath();

                modelo.addRow(new Object[]{nombre, tipo, fecha, ruta});
            }
        }

        tbInformes.setModel(modelo);

        // Ocultamos la columna de ruta
        tbInformes.getColumnModel().getColumn(3).setMinWidth(0);
        tbInformes.getColumnModel().getColumn(3).setMaxWidth(0);
        tbInformes.getColumnModel().getColumn(3).setWidth(0);

        // Diseño de la tabla
        tbInformes.setRowHeight(36);
        tbInformes.setFont(new Font("Microsoft JhengHei", Font.PLAIN, 14));
        tbInformes.getTableHeader().setFont(new Font("Microsoft JhengHei", Font.PLAIN, 14));

        DefaultTableCellRenderer centrado = new DefaultTableCellRenderer();
        centrado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        DefaultTableCellRenderer izquierda = new DefaultTableCellRenderer();
        izquierda.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        // Nombre izquierda
        tbInformes.getColumnModel().getColumn(0).setCellRenderer(izquierda);
        // Tipo centro
        tbInformes.getColumnModel().getColumn(1).setCellRenderer(centrado);
        // Fecha centro
        tbInformes.getColumnModel().getColumn(2).setCellRenderer(centrado);
    }

    private String obtenerTipoInforme(String nombreArchivo) {
        if (nombreArchivo.startsWith("informe_averia_")) {
            return "Informe de avería";
        } else if (nombreArchivo.startsWith("informe_maquinas_estado_")) {
            return "Informe de estado de maquinaria";
        } else if (nombreArchivo.startsWith("informe_rendimiento_tecnico")) {
            return "Informe de rendimiento tecnico";
        } else {
            return "Otro";
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new PanelImgFondo("/recursos/fondoFormularios.png");
        jPanel2 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        btnVerInforme = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbInformes = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btnEliminarInforme = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Informes");

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        btnVerInforme.setBackground(new java.awt.Color(58, 181, 235));
        btnVerInforme.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        btnVerInforme.setForeground(new java.awt.Color(255, 255, 255));
        btnVerInforme.setText("Ver");
        btnVerInforme.setBorderPainted(false);
        btnVerInforme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerInformeActionPerformed(evt);
            }
        });

        tbInformes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbInformes);

        jLabel1.setFont(new java.awt.Font("Microsoft JhengHei", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 204));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Informes generados");

        btnEliminarInforme.setBackground(new java.awt.Color(204, 0, 0));
        btnEliminarInforme.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        btnEliminarInforme.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminarInforme.setText("Eliminar");
        btnEliminarInforme.setBorderPainted(false);
        btnEliminarInforme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarInformeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnEliminarInforme, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(311, 311, 311)
                        .addComponent(btnVerInforme, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(50, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVerInforme, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminarInforme, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(101, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(42, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVerInformeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerInformeActionPerformed
        try {
            int fila = tbInformes.getSelectedRow();

            if (fila == -1) {
                JOptionPane.showMessageDialog(this,
                        "Selecciona un informe primero");
                return;
            }

            String nombreArchivo = (String) tbInformes.getValueAt(fila, 0);
            String[] partes = nombreArchivo.split("_");

            panelInformes ventana;

            if (nombreArchivo.startsWith("informe_averia_")) {
                int idAveria = Integer.parseInt(partes[2]);
                ventana = new panelInformes(null, true, "averia", idAveria);

            } else if (nombreArchivo.startsWith("informe_maquinas_estado_")) {
                int idEstado = Integer.parseInt(partes[3]);
                ventana = new panelInformes(null, true, "maquinas_estado", idEstado);

            } else if (nombreArchivo.startsWith("informe_rendimiento_tecnico")) {
                ventana = new panelInformes(null, true, "tecnicos", 0);

            } else {
                JOptionPane.showMessageDialog(this,
                        "El tipo de informe no esta soportado.");
                return;
            }

            ventana.setLocationRelativeTo(this);
            ventana.setVisible(true);

        } catch (Exception e) {
            logger.log(java.util.logging.Level.SEVERE, "Error al abrir informe", e);

            JOptionPane.showMessageDialog(this,
                    "No se pudo abrir el informe");
        }
    }//GEN-LAST:event_btnVerInformeActionPerformed

    private void btnEliminarInformeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarInformeActionPerformed
        try {
            int fila = tbInformes.getSelectedRow();

            if (fila == -1) {
                JOptionPane.showMessageDialog(this,
                        "Debes seleccionar un informe de la tabla.",
                        "Eliminar informe",
                        JOptionPane.WARNING_MESSAGE);
                return;
            }

            String ruta = (String) tbInformes.getValueAt(fila, 3);
            File archivo = new File(ruta);

            if (!archivo.exists()) {
                JOptionPane.showMessageDialog(this,
                        "El archivo no existe o ya fue eliminado.",
                        "Eliminar informe",
                        JOptionPane.WARNING_MESSAGE);

                cargarInformes();
                return;
            }

            int respuesta = JOptionPane.showConfirmDialog(this,
                    "¿Deseas eliminar el informe seleccionado?",
                    "Confirmar eliminacion",
                    JOptionPane.YES_NO_OPTION,
                    JOptionPane.WARNING_MESSAGE);

            if (respuesta == JOptionPane.YES_OPTION) {
                boolean eliminado = archivo.delete();

                if (eliminado) {
                    JOptionPane.showMessageDialog(this,
                            "Informe eliminado correctamente.",
                            "Eliminar informe",
                            JOptionPane.INFORMATION_MESSAGE);

                    cargarInformes();
                } else {
                    JOptionPane.showMessageDialog(this,
                            "No se pudo eliminar el informe.",
                            "Eliminar informe",
                            JOptionPane.ERROR_MESSAGE);
                }
            }

        } catch (Exception e) {
            logger.log(java.util.logging.Level.SEVERE, "Error al eliminar informe", e);

            JOptionPane.showMessageDialog(this,
                    "Se produjo un error al eliminar el informe.",
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnEliminarInformeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEliminarInforme;
    private javax.swing.JButton btnVerInforme;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable tbInformes;
    // End of variables declaration//GEN-END:variables
}
