/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import com.formdev.flatlaf.FlatLightLaf;
import controlador.GestionUsuarioControlador;
import controlador.LoginControlador;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import modelo.Usuario;
import java.util.prefs.Preferences;

/**
 *
 * @author Asus
 */
public class vLogin extends javax.swing.JFrame {

    //Atributos de la clase
    private final LoginControlador loginControlador;
    //variables para el metodo de recordar email del usuario que se loguea 
    private static final String PREF_NODE = "TYN_Solutions_Login";
    private static final String KEY_EMAIL = "email_recordado";
    private static final String KEY_RECORDAR = "recordar_usuario";

    /**
     * Creates new form vLogin
     */
    public vLogin(LoginControlador loginControlador) {
        initComponents();
        this.loginControlador = loginControlador;

        //Metodo para recordar el email del usuario 
        cargarUsuarioRecordado();

        Image icono = new ImageIcon(getClass().getResource("/recursos/isotipo.png")).getImage();
        this.setIconImage(icono);
    }

    /**
     * El metodo cargarUsuarioRecordado() se ejecuta cuando se abre la ventana
     * de login. Comprueba si anteriormente el usuario marco la opcion recordar
     * usuario. Si es asi, carga automaticamente el email en el campo de texto y
     * marca el checkbox. Si no hay nada guardado no hace nada
     */
    private void cargarUsuarioRecordado() {
        Preferences prefs = Preferences.userRoot().node(PREF_NODE);

        boolean recordar = prefs.getBoolean(KEY_RECORDAR, false);
        String email = prefs.get(KEY_EMAIL, "");

        if (recordar && email != null && !email.isEmpty()) {
            txtEmail.setText(email);
            chkRecordarUsuario.setSelected(true);
        } else {
            chkRecordarUsuario.setSelected(false);
        }
    }

    /**
     * Este metodo se ejecuta despues de un login correcto. Si el checkbox esta
     * marcado, guarda el email en el sistema para que aparezca la proxima vez.
     * Si no esta marcado, elimina el email guardado
     *
     * esto es pocible porque utilizmao la clase Preferences ya que nos permite
     * guardar pequeños datos de configuracion en el sistema operativo del
     * usuario sin necesidad de crear una base de datos ni un fichero
     * manualmente
     */
    private void guardarUsuarioRecordado() {

        Preferences prefs = Preferences.userRoot().node(PREF_NODE);

        boolean recordar = chkRecordarUsuario.isSelected();
        String email = txtEmail.getText();

        if (recordar) {
            prefs.putBoolean(KEY_RECORDAR, true);
            prefs.put(KEY_EMAIL, email);
        } else {
            prefs.putBoolean(KEY_RECORDAR, false);
            prefs.remove(KEY_EMAIL);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new PanelImgFondo("/recursos/fondo_con_logo.png");
        formulario = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        btnLogin = new javax.swing.JButton();
        btnRecuperar = new javax.swing.JButton();
        chkRecordarUsuario = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 208, 217));
        jPanel1.setPreferredSize(new java.awt.Dimension(1200, 800));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        formulario.setBackground(new java.awt.Color(255, 255, 255));
        formulario.setPreferredSize(new java.awt.Dimension(400, 400));
        formulario.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Bienvenido ");
        formulario.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, -1, -1));
        formulario.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 310, -1));

        jLabel1.setFont(new java.awt.Font("Microsoft YaHei Light", 0, 14)); // NOI18N
        jLabel1.setText("Email: ");
        formulario.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 60, -1));
        formulario.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 310, -1));

        jLabel2.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 14)); // NOI18N
        jLabel2.setText("Contraseña: ");
        formulario.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 120, -1));

        btnLogin.setBackground(new java.awt.Color(58, 181, 235));
        btnLogin.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        btnLogin.setForeground(new java.awt.Color(255, 255, 255));
        btnLogin.setText("Entrar");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        formulario.add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 90, 90, -1));

        btnRecuperar.setBackground(new java.awt.Color(199, 234, 249));
        btnRecuperar.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 12)); // NOI18N
        btnRecuperar.setForeground(new java.awt.Color(39, 155, 230));
        btnRecuperar.setText("¿Has olvidado tu contraseña?");
        btnRecuperar.setBorderPainted(false);
        btnRecuperar.setFocusPainted(false);
        btnRecuperar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRecuperarActionPerformed(evt);
            }
        });
        formulario.add(btnRecuperar, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 200, -1, -1));

        chkRecordarUsuario.setText("Recordar usuario ");
        formulario.add(chkRecordarUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, -1, -1));

        jPanel1.add(formulario, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, 610, 250));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed

        //Llama al método del controlador para comprobar si el usuario existe
        // Obtener datos introducidos
        String email = txtEmail.getText().trim();
        String password = new String(txtPassword.getPassword()).trim();

        // Validacion basica de campos vacios
        if (email.isEmpty() || password.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                    "Debe introducir email y contraseña",
                    "Campos vacios",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }
        // Llamada al controlador
        Usuario usuario = loginControlador.accederAplicacion(email, password);

        if (usuario == null) {
            // Login incorrecto
            JOptionPane.showMessageDialog(this,
                    "Credenciales incorrectas",
                    "Error de autenticacion",
                    JOptionPane.WARNING_MESSAGE);

        } else {
            // Login correcto
            JOptionPane.showMessageDialog(this,
                    "Bienvenido " + usuario.getNombre(),
                    "Acceso concedido",
                    JOptionPane.INFORMATION_MESSAGE);

            //Llamamos al metodo para que recuerde el email del usuario que se ha accedido 
            guardarUsuarioRecordado();

            // Abrir ventana principal
            int codigoRol = usuario.getCodigoRolFK().getCodigoRol();

            if (codigoRol == 701) {
                vHomeAdmin vHome = new vHomeAdmin();
                vHome.setVisible(true);
            } else if (codigoRol == 702) {
                vHomeOper vHome = new vHomeOper();
                vHome.setVisible(true);
            } else {
                JOptionPane.showMessageDialog(this,
                        "Credenciales incorrectas",
                        "Error de autenticacion",
                        JOptionPane.WARNING_MESSAGE);
            }
            // Cerrar login
            this.dispose();
        }
    }//GEN-LAST:event_btnLoginActionPerformed

    private void btnRecuperarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecuperarActionPerformed

        String emailSolicitud;

        //Solicitamos el dato
        emailSolicitud = JOptionPane.showInputDialog(this, "Ingresa tu correo corporativo: ",
                "Restablecimiento de contraseña",
                JOptionPane.QUESTION_MESSAGE);

        if (emailSolicitud != null) {
            // Pulso aceptar
            if (!emailSolicitud.trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Se ha enviado tu solicitud de cambio de contraseña",
                        "Restablecimiento de contraseña",
                        JOptionPane.INFORMATION_MESSAGE);
                loginControlador.restablecerPassword(emailSolicitud);
            } else {
                JOptionPane.showMessageDialog(this, "Debe rellenar el campo",
                        "Restablecimiento de contraseña",
                        JOptionPane.INFORMATION_MESSAGE);
            }
            // Pulso cancelar o cerro
        } else {
            JOptionPane.showMessageDialog(this, "Operación cancelada",
                    "Restablecimiento de contraseña",
                    JOptionPane.INFORMATION_MESSAGE);
        }

    }//GEN-LAST:event_btnRecuperarActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnRecuperar;
    private javax.swing.JCheckBox chkRecordarUsuario;
    private javax.swing.JPanel formulario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JPasswordField txtPassword;
    // End of variables declaration//GEN-END:variables
}
