/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista.admin;

import java.util.List;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import javax.swing.RowFilter;
import javax.swing.JOptionPane;

import controlador.AveriaControlador;
import modelo.Averia;

/**
 * Ventana principal para la gestión de Averías.
 * Muestra el listado general y actúa como panel de control para CRUD y filtros.
 * @author yosue
 */
public class AveriaListar extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AveriaListar.class.getName());

    // --- Controladores y Modelos ---
    private final AveriaControlador controladorAveria;
    private DefaultTableModel modeloTabla;
    private TableRowSorter<DefaultTableModel> sorter;
    
    // --- Estados de Interfaz ---
    private boolean filtrosAplicados = false;
    
    /**
     * Creates new form vAdminViewAverias
     */
    public AveriaListar() {
        controladorAveria = new AveriaControlador();
        
        initComponents();
        
        // Configuraciones iniciales
        inicializarTabla();
        cargarDatos();
        configurarBuscador();
        
        // Centrar la ventana al abrir
        this.setLocationRelativeTo(null);
    }

    // =========================================================================
    // 1. CONFIGURACIÓN Y CARGA DE DATOS
    // =========================================================================

    private void inicializarTabla() {
        String[] columnas = {
            "Cód.", "Descripción", "Máquina", "Tipo Avería", 
            "F. Inicio", "F. Asignación", "F. Aceptación", "F. Fin",          
            "Estado", "Reportado Por", "Técnico", "Procedimiento"
        };

        // Modelo que impide la edición directa de celdas
        modeloTabla = new DefaultTableModel(null, columnas) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; 
            }
        };

        tablaAveria.setModel(modeloTabla);
        sorter = new TableRowSorter<>(modeloTabla);
        tablaAveria.setRowSorter(sorter);
        
        // Ajuste visual de la columna ID
        javax.swing.table.TableColumnModel columnModel = tablaAveria.getColumnModel();
        columnModel.getColumn(0).setPreferredWidth(40);
        columnModel.getColumn(0).setMaxWidth(60);
    }

    /**
     * Descarga todas las averías de la BD y refresca la tabla.
     */
    private void cargarDatos() {
        List<Object[]> datos = controladorAveria.listarAveriasParaVista();
        actualizarModeloTabla(datos);
    }

    /**
     * Método auxiliar para rellenar la tabla evitando duplicar código.
     */
    private void actualizarModeloTabla(List<Object[]> datos) {
        modeloTabla.setRowCount(0); // Limpia la tabla actual
        if (datos != null) {
            for (Object[] fila : datos) {
                modeloTabla.addRow(fila);
            }
        }
    }

    // =========================================================================
    // 2. LÓGICA DE FILTRADO LOCAL (Buscador Rápido)
    // =========================================================================

    private void configurarBuscador() {
        txtAveriaBuscar.getDocument().addDocumentListener(new DocumentListener() {
            @Override public void insertUpdate(DocumentEvent e) { filtrar(); }
            @Override public void removeUpdate(DocumentEvent e) { filtrar(); }
            @Override public void changedUpdate(DocumentEvent e) { filtrar(); }
        });
    }

    private void filtrar() {
        String texto = txtAveriaBuscar.getText();
        if (texto.trim().isEmpty()) {
            sorter.setRowFilter(null);
        } else {
            sorter.setRowFilter(RowFilter.regexFilter("(?i)" + texto));
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaAveria = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtAveriaBuscar = new javax.swing.JTextField();
        btnAveriaEliminar = new javax.swing.JButton();
        btnAveriaActualizar = new javax.swing.JButton();
        btnAveriaNueva = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        tgbtnFiltros = new javax.swing.JToggleButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tablaAveria.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaAveria);

        jLabel1.setText("Buscar avería:");

        btnAveriaEliminar.setBackground(new java.awt.Color(255, 153, 153));
        btnAveriaEliminar.setText("Eliminar avería");
        btnAveriaEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAveriaEliminarActionPerformed(evt);
            }
        });

        btnAveriaActualizar.setText("Actualizar avería");
        btnAveriaActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAveriaActualizarActionPerformed(evt);
            }
        });

        btnAveriaNueva.setText("Nueva avería");
        btnAveriaNueva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAveriaNuevaActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Gestión de averías");

        tgbtnFiltros.setText("Filtros");
        tgbtnFiltros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tgbtnFiltrosActionPerformed(evt);
            }
        });

        jMenu1.setText("Inicio");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Máquinas");
        jMenuBar1.add(jMenu2);

        jMenu3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jMenu3.setText("Averías");
        jMenuBar1.add(jMenu3);

        jMenu4.setText("Usuarios");
        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtAveriaBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(tgbtnFiltros)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAveriaNueva))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(20, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnAveriaActualizar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnAveriaEliminar))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1160, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(20, Short.MAX_VALUE))
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel2)
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtAveriaBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAveriaNueva)
                    .addComponent(tgbtnFiltros))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 570, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAveriaEliminar)
                    .addComponent(btnAveriaActualizar))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // =========================================================================
    // 3. EVENTOS DE BOTONES (CRUD y Filtros Avanzados)
    // =========================================================================
    
    private void btnAveriaNuevaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAveriaNuevaActionPerformed
        // 1. Crear la instancia del JDialog
        AveriaNueva ventanaNueva = new AveriaNueva(this, true);
        // 2. Centrar la ventana respecto a la pantalla o al padre
        ventanaNueva.setLocationRelativeTo(this);
        // 3. Mostrar la ventana
        ventanaNueva.setVisible(true);
        // 4. Refrescar la tabla al volver
        cargarDatos();
    }//GEN-LAST:event_btnAveriaNuevaActionPerformed

    private void btnAveriaActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAveriaActualizarActionPerformed
        try {
            // 1. Obtener la fila seleccionada (getSelectedRow coge la primera si hay varias)
            int filaVista = tablaAveria.getSelectedRow();

            if (filaVista == -1) {
                JOptionPane.showMessageDialog(this, 
                    "Por favor, selecciona una avería de la tabla para actualizar.", 
                    "Selección requerida", JOptionPane.WARNING_MESSAGE);
                return; 
            }

            // 2. Convertir índice por si hay filtros aplicados
            int filaModelo = tablaAveria.convertRowIndexToModel(filaVista);
            int idAveria = (int) modeloTabla.getValueAt(filaModelo, 0);

            // 3. Buscar la avería en la BD
            Averia averiaSeleccionada = controladorAveria.obtenerAveriaPorId(idAveria);

            if (averiaSeleccionada != null) {
                AveriaActualizar ventanaActualizar = new AveriaActualizar(this, true, averiaSeleccionada);
                ventanaActualizar.setLocationRelativeTo(this);
                ventanaActualizar.setVisible(true); // Se pausa aquí

                cargarDatos(); // Refrescar al volver
            } else {
                 JOptionPane.showMessageDialog(this, 
                    "No se pudo cargar la información de la avería seleccionada.\nEs posible que haya sido eliminada por otro usuario.", 
                    "Error de lectura", JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception e) {
            logger.log(java.util.logging.Level.SEVERE, "Error al preparar la actualización", e);
            JOptionPane.showMessageDialog(this, "Ocurrió un error inesperado.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnAveriaActualizarActionPerformed

    private void tgbtnFiltrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tgbtnFiltrosActionPerformed
        // ESTADO 1: Si ya hay filtros aplicados, el botón actúa para ELIMINARLOS
        if (filtrosAplicados) {
            cargarDatos(); // Recarga todo desde la BD
            tgbtnFiltros.setText("Filtros");
            filtrosAplicados = false;
        } 
        
        // ESTADO 2: Si NO hay filtros, el botón actúa para APLICARLOS (Abre el JDialog)
        else {
            AveriaFiltros ventanaFiltros = new AveriaFiltros(this, true);
            ventanaFiltros.setLocationRelativeTo(this);
            ventanaFiltros.setVisible(true); // El programa espera aquí

            // Si el usuario le dio a "Aplicar filtros" en el JDialog...
            if (ventanaFiltros.isAplicarFiltros()) {
                
                // 1. Extraemos los valores del JDialog
                Integer id = ventanaFiltros.getFiltroId();
                Integer idMaq = ventanaFiltros.getFiltroMaquina();
                Integer idUsu = ventanaFiltros.getFiltroUsuario();
                Integer idTec = ventanaFiltros.getFiltroTecnico();
                Integer idTipo = ventanaFiltros.getFiltroTipo();
                java.time.LocalDateTime fIni = ventanaFiltros.getFiltroFechaReporte();
                java.time.LocalDateTime fFin = ventanaFiltros.getFiltroFechaFinal();
                
                // 2. Traemos los datos filtrados
                List<Object[]> datosFiltrados = controladorAveria.obtenerAveriasFiltradas(
                    id, null, fIni, fFin, idUsu, idTec, idMaq, idTipo
                );
                
                // 3. COMPROBAMOS LOS RESULTADOS
                if (datosFiltrados != null && !datosFiltrados.isEmpty()) {
                    
                    // Hay resultados: Vaciamos la tabla y los pintamos
                    modeloTabla.setRowCount(0); 
                    for (Object[] fila : datosFiltrados) {
                        modeloTabla.addRow(fila);
                    }
                    
                    // Convertimos el botón a "Eliminar filtros"
                    tgbtnFiltros.setText("Eliminar filtros");
                    filtrosAplicados = true;
                    // El botón se queda hundido, que es lo que queremos.
                    
                } else {
                    // NO HAY RESULTADOS
                    javax.swing.JOptionPane.showMessageDialog(this, 
                        "No se encontró ninguna avería con los filtros indicados.", 
                        "Sin resultados", 
                        javax.swing.JOptionPane.INFORMATION_MESSAGE);
                        
                    // Nos aseguramos de que la tabla muestra todo y el botón se reinicia
                    cargarDatos(); 
                    tgbtnFiltros.setText("Filtros");
                    filtrosAplicados = false;
                    tgbtnFiltros.setSelected(false);
                }
            } 
            else { 
                // El usuario cerró la ventana en la 'X' sin darle a "Aplicar filtros"
                tgbtnFiltros.setSelected(false); 
                
                // Por si acaso, confirmamos el texto y el estado
                tgbtnFiltros.setText("Filtros");
                filtrosAplicados = false;
            }
        }
    }//GEN-LAST:event_tgbtnFiltrosActionPerformed

    private void btnAveriaEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAveriaEliminarActionPerformed
        try {
            int filaVista = tablaAveria.getSelectedRow();

            if (filaVista == -1) {
                JOptionPane.showMessageDialog(this, 
                    "Por favor, selecciona una avería de la tabla para eliminar.", 
                    "Selección requerida", JOptionPane.WARNING_MESSAGE);
                return;
            }

            int filaModelo = tablaAveria.convertRowIndexToModel(filaVista);
            int idAveria = (int) modeloTabla.getValueAt(filaModelo, 0);
            String descripcion = (String) modeloTabla.getValueAt(filaModelo, 1);

            int respuesta = JOptionPane.showConfirmDialog(this, 
                "¿Estás seguro de que deseas eliminar permanentemente la avería #" + idAveria + ":\n\"" + descripcion + "\"?\n\nEsta acción no se puede deshacer.", 
                "Confirmar eliminación", 
                JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);

            if (respuesta == JOptionPane.YES_OPTION) {
                boolean exito = controladorAveria.eliminarAveria(idAveria);

                if (exito) {
                    JOptionPane.showMessageDialog(this, "Avería eliminada con éxito.");
                    cargarDatos(); 
                } else {
                    JOptionPane.showMessageDialog(this, 
                        "No se pudo eliminar la avería.\nEs posible que tenga datos asociados o ya no exista.", 
                        "Error al eliminar", JOptionPane.ERROR_MESSAGE);
                }
            }
        } catch (Exception e) {
            logger.log(java.util.logging.Level.SEVERE, "Error al intentar eliminar", e);
            JOptionPane.showMessageDialog(this, "Ocurrió un error inesperado al intentar eliminar.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnAveriaEliminarActionPerformed

    // =========================================================================
    // 4. CÓDIGO AUTOGENERADO (Diseño de la Interfaz)
    // =========================================================================

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAveriaActualizar;
    private javax.swing.JButton btnAveriaEliminar;
    private javax.swing.JButton btnAveriaNueva;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaAveria;
    private javax.swing.JToggleButton tgbtnFiltros;
    private javax.swing.JTextField txtAveriaBuscar;
    // End of variables declaration//GEN-END:variables
}
