/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package vista.admin.maquinas;

import controlador.GestionMaquinasControlador;
import java.util.Date;
import javax.swing.JOptionPane;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import javax.swing.DefaultComboBoxModel;
import modelo.Estado;
import modelo.TipoMaquinaria;
import modelo.Maquinaria;

/**
 * REVISAR: primero muestra la lista!
 * @author Nereida Rodríguez Orenes 2ºDAM
 */
public class ActualizarMaquina extends javax.swing.JDialog {
    private GestionMaquinasControlador contr = new GestionMaquinasControlador();
    private final Map<String, Integer> estadoDescToId = new LinkedHashMap<>();
    private final Map<String, Integer> tipoDescToId = new LinkedHashMap<>();
    private Maquinaria maquinaActual; //la que estoy editando
    /**
     * Creates new form NuevaMaquina
     */
    public ActualizarMaquina(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        cargarCombosDesdeBD();
        cbbStatus.addActionListener(e -> aplicarReglaFechaBaja()); //cada vez que cambie el estado
        aplicarReglaFechaBaja(); //cuando se abra el diálogo
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        cbbStatus = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        spFechaAlta = new javax.swing.JSpinner();
        jLabel4 = new javax.swing.JLabel();
        cbbTipo = new javax.swing.JComboBox<>();
        btnActualizarMaquina = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        spFechaBaja = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Fixora");

        jPanel1.setBackground(new java.awt.Color(204, 208, 217));

        jLabel1.setText("Nombre: ");

        cbbStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Operativa", "Averiada", "Mantenimiento", "Fuera" }));

        jLabel2.setText("Estado: ");

        jLabel3.setText("Fecha alta:");

        spFechaAlta.setModel(new javax.swing.SpinnerDateModel());

        jLabel4.setText("Tipo: ");
        jLabel4.setToolTipText("");

        cbbTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "cortes y arranque de material mecanizado", "perforación y operaciones de agujeros", "abrasivo y acabado superficial", "corte por separacion", "conformado y deformación sin arranque de viruta", "union y ensamblaje", "tratamiento y acondicionamiento", "procesos especificos" }));

        btnActualizarMaquina.setText("Actualizar máquina");
        btnActualizarMaquina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarMaquinaActionPerformed(evt);
            }
        });

        jLabel5.setText("Fecha baja: ");

        spFechaBaja.setModel(new javax.swing.SpinnerDateModel());
        spFechaBaja.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(118, 118, 118)
                .addComponent(btnActualizarMaquina)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(spFechaAlta)
                            .addComponent(cbbTipo, 0, 287, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cbbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(12, 12, 12)
                        .addComponent(spFechaBaja)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(spFechaAlta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cbbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(spFechaBaja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(98, 98, 98)
                .addComponent(btnActualizarMaquina)
                .addContainerGap(219, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnActualizarMaquinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarMaquinaActionPerformed
        if (maquinaActual == null) {
            JOptionPane.showMessageDialog(this, "No hay máquina cargada para actualizar. Seleccione un máquina en la pantalla anterior.",
                    "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        String nomMaq = txtNombre.getText();

        String estadoDesc = (String) cbbStatus.getSelectedItem();
        String tipoDesc = (String) cbbTipo.getSelectedItem();

        Integer estadoId = estadoDescToId.get(estadoDesc);
        Integer tipoId = tipoDescToId.get(tipoDesc);

        Date fechaAlta = (Date) spFechaAlta.getValue();
        Date fechaBaja = spFechaBaja.isEnabled() ? (Date) spFechaBaja.getValue() : null;

        if (estadoId == null || tipoId == null) {
            JOptionPane.showMessageDialog(this, "No se han podido obtener los IDs del estado o tipo de máquina.",
                    "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        boolean ok = contr.actualizarMaquina(
                maquinaActual.getCodigoMaquinaria(),
                nomMaq,
                estadoId,
                tipoId,
                fechaAlta,
                fechaBaja
        );

        if (ok) {
            JOptionPane.showMessageDialog(this, "Máquina actualizada con éxito",
                    "Actualización realizada", JOptionPane.INFORMATION_MESSAGE);
            dispose();
        } else {
            JOptionPane.showMessageDialog(this,
                    "Revise los datos: alguno no es correcto. ¿La fecha de baja es posterior a la de alta?",
                    "Error de actualización", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnActualizarMaquinaActionPerformed

    //comboboxes
    private void cargarCombosDesdeBD() {
        // --- ESTADOS ---
        DefaultComboBoxModel<String> modelEstados = new DefaultComboBoxModel<>();
        estadoDescToId.clear();

        List<Estado> estados = contr.listarEstado();
        for (Estado e : estados) {
            String desc = e.getDescripcionEstado(); 
            int id = e.getCodigoEstado();          

            modelEstados.addElement(desc);
            estadoDescToId.put(desc, id);
        }
        cbbStatus.setModel(modelEstados);

        // --- TIPOS ---
        DefaultComboBoxModel<String> modelTipos = new DefaultComboBoxModel<>();
        tipoDescToId.clear();

        List<TipoMaquinaria> tipos = contr.listarTipoMaquinaria();
        for (TipoMaquinaria t : tipos) {
            String desc = t.getDescripcionMaq();      
            int id = t.getCodigoTipoMaquinaria();      

            modelTipos.addElement(desc);
            tipoDescToId.put(desc, id);
        }
        cbbTipo.setModel(modelTipos);
    }
    
    //cargar máquina seleccionada en la vista anterior
    public void setMaquina(Maquinaria m) {
        this.maquinaActual = m;

        txtNombre.setText(m.getNombre());

        if (m.getFechaAlta() != null) {
            spFechaAlta.setValue(java.sql.Date.valueOf(m.getFechaAlta()));
        }

        if (m.getFechaBaja() != null) {
            spFechaBaja.setValue(java.sql.Date.valueOf(m.getFechaBaja()));
        }

        if (m.getEstado() != null) {
            String estadoDesc = buscarDescPorId(estadoDescToId, m.getEstado().getCodigoEstado());
            if (estadoDesc != null) {
                cbbStatus.setSelectedItem(estadoDesc);
            }
        }

        if (m.getTipoMaquinaria() != null) {
            String tipoDesc = buscarDescPorId(tipoDescToId, m.getTipoMaquinaria().getCodigoTipoMaquinaria());
            if (tipoDesc != null) {
                cbbTipo.setSelectedItem(tipoDesc);
            }
        }

        aplicarReglaFechaBaja();
    }
    private String buscarDescPorId(Map<String, Integer> map, int id) {
        for (Map.Entry<String, Integer> e : map.entrySet()) {
            if (e.getValue() != null && e.getValue() == id) return e.getKey();
        }
        return null;
    }
    
    //reglas de fechas -> solo va a estar habilitado el spinner de fecha de baja si la máquina está "fuera de servicio"
    private void aplicarReglaFechaBaja() {
        String estado = (String) cbbStatus.getSelectedItem();
        boolean esFuera = estado != null && estado.toLowerCase().contains("fuera");

        spFechaBaja.setEnabled(esFuera);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizarMaquina;
    private javax.swing.JComboBox<String> cbbStatus;
    private javax.swing.JComboBox<String> cbbTipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSpinner spFechaAlta;
    private javax.swing.JSpinner spFechaBaja;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
