/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package vista.admin.maquinas;

import controlador.GestionEstadoMaquinaControlador;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import javax.swing.SpinnerNumberModel;

/**
 *
 * @author Nereida Rodríguez Orenes 2ºDAM
 */
public class NuevoEstadoMaquina extends javax.swing.JDialog {
    private final GestionEstadoMaquinaControlador contr = new GestionEstadoMaquinaControlador();
    /**
     * Creates new form NuevoTipoMaquina
     */
    public NuevoEstadoMaquina(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        inicializarSpinnerCodigoEstado();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtDescEstado = new javax.swing.JTextField();
        btnCrearEstado = new javax.swing.JButton();
        txtPrefijo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        spCodigo = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Nuevo Estado de Máquina");

        jLabel2.setText("Descripción (corta):");

        btnCrearEstado.setText("Crear");
        btnCrearEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearEstadoActionPerformed(evt);
            }
        });

        txtPrefijo.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtPrefijo.setText("8");
        txtPrefijo.setEnabled(false);

        jLabel3.setText("Código: ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(162, 162, 162)
                        .addComponent(btnCrearEstado))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(38, 38, 38)
                                .addComponent(txtPrefijo, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(spCodigo))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(txtDescEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(83, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel1)
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPrefijo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(spCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtDescEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(btnCrearEstado)
                .addGap(72, 72, 72))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCrearEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearEstadoActionPerformed
        String id = obtenerCodigoEstadoCompleto();
        String desc = txtDescEstado.getText();

        if (desc.isEmpty()) {
            JOptionPane.showMessageDialog(
                this,
                "La descripción no puede estar vacía.",
                "Error de validación",
                JOptionPane.WARNING_MESSAGE
            );
            return;
        }

        boolean flag = contr.insertarEstado(id, desc);

        if (flag) {
            JOptionPane.showMessageDialog(
                this,
                "Estado nuevo creado con éxito.",
                "Creación exitosa",
                JOptionPane.INFORMATION_MESSAGE
            );
            
        } else {
            JOptionPane.showMessageDialog(
                this,
                "No se ha podido insertar el estado.\nComprueba que el ID no exista y que los datos sean válidos.",
                "Error de inserción",
                JOptionPane.ERROR_MESSAGE
            );
        }
    }//GEN-LAST:event_btnCrearEstadoActionPerformed

    //Spinner
    /**
     * Aquí hemos hecho que el spinner empiece en 1, tenga como mínimo 1, como
     * máximo 99 y avance de uno en uno. Después le ponemos el formato "00" para
     * que visualmente se vea 01, 02, 03... hasta 99.
     */
    private void inicializarSpinnerCodigoEstado() {
        SpinnerNumberModel modeloCodigoEstado = new SpinnerNumberModel(1, 1, 99, 1);
        spCodigo.setModel(modeloCodigoEstado);

        JSpinner.NumberEditor editorCodigoEstado = new JSpinner.NumberEditor(spCodigo, "00");
        spCodigo.setEditor(editorCodigoEstado);
    }

    private String obtenerNumeroEstadoFormateado() {
        int numeroEstado = (int) spCodigo.getValue();
        return String.format("%02d", numeroEstado);
    }

    private String obtenerCodigoEstadoCompleto() {
        String numeroEstadoFormateado = obtenerNumeroEstadoFormateado();
        return "8" + numeroEstadoFormateado;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCrearEstado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSpinner spCodigo;
    private javax.swing.JTextField txtDescEstado;
    private javax.swing.JTextField txtPrefijo;
    // End of variables declaration//GEN-END:variables
}
