/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package vista.admin.maquinas;

import com.formdev.flatlaf.extras.FlatSVGIcon;
import controlador.GestionTipoMaquinaControlador;
import java.awt.Image;
import java.awt.Insets;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import javax.swing.SpinnerNumberModel;
import vista.PanelImgFondo;

/**
 *
 * @author Nereida Rodríguez Orenes 2ºDAM
 */
public class NuevoTipoMaquina extends javax.swing.JDialog {

    private final GestionTipoMaquinaControlador contr = new GestionTipoMaquinaControlador();

    /**
     * Creates new form NuevoTipoMaquina
     */
    public NuevoTipoMaquina(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        inicializarSpinnerNumeroTM();
        mostrarImagenes();
    }

    public void mostrarImagenes() {
        //icno de la app
        Image icono = new ImageIcon(getClass().getResource("/recursos/isotipo.png")).getImage();
        this.setIconImage(icono);
        // Centrar ventana en pantalla
        setLocationRelativeTo(null);
        // Evitar que el usuario cambie el tamaño
        setResizable(false);

        //ICONOS LtextField
        //Campo nombre de la maquina
        FlatSVGIcon iconoCodigo = new FlatSVGIcon("recursos/iconos/icnNumerico.svg", 16, 16);
        txtPrefijo.putClientProperty("JTextField.leadingIcon", iconoCodigo);
        txtPrefijo.putClientProperty("JComponent.padding", new Insets(5, 8, 5, 8));
        txtPrefijo.putClientProperty("JTextField.placeholderText", "Código Tipo:  3");
        // descripcion txtDescEstado
        FlatSVGIcon iconoDescrpcion = new FlatSVGIcon("recursos/iconos/icnEtiqueta.svg", 16, 16);
        txtDescTM.putClientProperty("JTextField.leadingIcon", iconoDescrpcion);
        txtDescTM.putClientProperty("JComponent.padding", new Insets(5, 8, 5, 8));
        txtDescTM.putClientProperty("JTextField.placeholderText", "Descripción del tipo: ");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new PanelImgFondo("/recursos/fondoFormularios.png");
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtDescTM = new javax.swing.JTextField();
        btnCrearTM = new javax.swing.JButton();
        txtPrefijo = new javax.swing.JTextField();
        spCodigo = new javax.swing.JSpinner();
        jSeparator1 = new javax.swing.JSeparator();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Nuevo tipo de máquina");

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Microsoft JhengHei", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 204));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Nuevo tipo de máquina");

        txtDescTM.setBackground(new java.awt.Color(237, 243, 251));

        btnCrearTM.setBackground(new java.awt.Color(58, 181, 235));
        btnCrearTM.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        btnCrearTM.setForeground(new java.awt.Color(255, 255, 255));
        btnCrearTM.setText("Crear");
        btnCrearTM.setBorderPainted(false);
        btnCrearTM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearTMActionPerformed(evt);
            }
        });

        txtPrefijo.setEditable(false);
        txtPrefijo.setBackground(new java.awt.Color(237, 243, 251));
        txtPrefijo.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtPrefijo.setText("3");
        txtPrefijo.setEnabled(false);

        btnCancelar.setBackground(new java.awt.Color(234, 242, 251));
        btnCancelar.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(67, 113, 177));
        btnCancelar.setText("Cancelar");
        btnCancelar.setBorderPainted(false);
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jSeparator1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(117, 117, 117)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCrearTM, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtDescTM)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txtPrefijo, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                        .addComponent(spCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(99, 99, 99))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(99, 99, 99)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtPrefijo, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(spCodigo))
                .addGap(61, 61, 61)
                .addComponent(txtDescTM, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 105, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCrearTM, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(83, 83, 83))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(101, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(99, 99, 99))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(43, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCrearTMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearTMActionPerformed
        //mandar el código formateado con los métodos del Spinner
        String id = obtenerCodigoTMCompleto();
        String desc = txtDescTM.getText();
        //mandar texto de la descripción
        boolean flag = contr.insertarTipoMaquinaria(id, desc);
        if (desc.isEmpty()) {
            JOptionPane.showMessageDialog(
                    this,
                    "La descripción no puede estar vacía",
                    "Error de validación",
                    JOptionPane.WARNING_MESSAGE
            );
            return;
        }

        if (flag) {
            JOptionPane.showMessageDialog(
                    this,
                    "Tipo de máquina nuevo creado con éxito",
                    "Creación exitosa",
                    JOptionPane.INFORMATION_MESSAGE
            );
        } else {
            JOptionPane.showMessageDialog(
                    this,
                    "No se ha podido insertar el tipo de maquinaria.\nComprueba que el ID no exista y que los datos sean válidos.",
                    "Error de inserción",
                    JOptionPane.ERROR_MESSAGE
            );
        }
    }//GEN-LAST:event_btnCrearTMActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        int respuesta = JOptionPane.showConfirmDialog(this, "¿Deseas cancelar la operación? Los cambios no se guardarán.", "Cancelar operación", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
        if (respuesta == JOptionPane.YES_OPTION) {
            dispose();
        }
    }//GEN-LAST:event_btnCancelarActionPerformed

    //Spinner
    /**
     * Aquí hemos hecho que el spinner empiece en 1, tenga como mínimo 1, como
     * máximo 99 y avance de uno en uno. Después le ponemos el formato "00" para
     * que visualmente se vea 01, 02, 03... hasta 99.
     */
    private void inicializarSpinnerNumeroTM() {
        SpinnerNumberModel modeloNumeroTM = new SpinnerNumberModel(1, 1, 99, 1);
        spCodigo.setModel(modeloNumeroTM);

        JSpinner.NumberEditor editorNumeroTM = new JSpinner.NumberEditor(spCodigo, "00");
        spCodigo.setEditor(editorNumeroTM);
    }

    private String obtenerNumeroTMFormateado() {
        int numeroTM = (int) spCodigo.getValue();
        String numeroTMFormateado = String.format("%02d", numeroTM);
        return numeroTMFormateado;
    }

    private String obtenerCodigoTMCompleto() {
        String numeroTMFormateado = obtenerNumeroTMFormateado();
        String codigoTMCompleto = "3" + numeroTMFormateado;
        return codigoTMCompleto;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnCrearTM;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSpinner spCodigo;
    private javax.swing.JTextField txtDescTM;
    private javax.swing.JTextField txtPrefijo;
    // End of variables declaration//GEN-END:variables
}
