/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package vista.admin.usuario;

import com.formdev.flatlaf.extras.FlatSVGIcon;
import controlador.GestionRolControlador;
import java.awt.Image;
import java.awt.Insets;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import javax.swing.SpinnerNumberModel;
import vista.PanelImgFondo;

/**
 *
 * @author Netri
 */
public class CrearRol extends javax.swing.JDialog {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CrearRol.class.getName());
    private final GestionRolControlador gestionRolControlador;
    private final GestionRol gestionRol;

    /**
     * Creates new form CrearRol
     */
    public CrearRol(java.awt.Frame parent, boolean modal, GestionRolControlador gestionRolControlador, GestionRol gestionRol) {
        super(parent, modal);
        initComponents();
        mostrarImagenes();
        this.gestionRol = gestionRol;
        this.gestionRolControlador = gestionRolControlador;
        inicializarSpinnerNumeroRol();
    }

    public void mostrarImagenes() {
        //icno de la app
        Image icono = new ImageIcon(getClass().getResource("/recursos/isotipo.png")).getImage();
        this.setIconImage(icono);
        this.setLocationRelativeTo(null);

        //ICONOS LtextField
        //Campo Codigo rol 
        FlatSVGIcon iconoCodigo = new FlatSVGIcon("recursos/iconos/icnNumerico.svg", 16, 16);
        txtCodigoRol.putClientProperty("JTextField.leadingIcon", iconoCodigo);
        txtCodigoRol.putClientProperty("JComponent.padding", new Insets(5, 8, 5, 8));
        txtCodigoRol.putClientProperty("JTextField.placeholderText", "Código Rol:  7 ");
        //Campo descripcion rol
        FlatSVGIcon iconoDescripcion = new FlatSVGIcon("recursos/iconos/icnEtiqueta.svg", 16, 16);
        txtDescripcionRol.putClientProperty("JTextField.leadingIcon", iconoDescripcion);
        txtDescripcionRol.putClientProperty("JComponent.padding", new Insets(5, 8, 5, 8));
        txtDescripcionRol.putClientProperty("JTextField.placeholderText", "Nombre del rol: ");
    }

    /**
     * Aquí hemos hecho que el spinner empiece en 1, tenga como mínimo 1, como
     * máximo 99 y avance de uno en uno. Después le ponemos el formato "00" para
     * que visualmente se vea 01, 02, 03... hasta 99.
     */
    private void inicializarSpinnerNumeroRol() {
        SpinnerNumberModel modeloNumeroRol = new SpinnerNumberModel(1, 1, 99, 1);
        spnNumeroRol.setModel(modeloNumeroRol);

        JSpinner.NumberEditor editorNumeroRol = new JSpinner.NumberEditor(spnNumeroRol, "00");
        spnNumeroRol.setEditor(editorNumeroRol);
    }

    private String obtenerNumeroRolFormateado() {
        int numeroRol = (int) spnNumeroRol.getValue();
        String numeroRolFormateado = String.format("%02d", numeroRol);
        return numeroRolFormateado;
    }

    private String obtenerCodigoRolCompleto() {
        String numeroRolFormateado = obtenerNumeroRolFormateado();
        String codigoRolCompleto = "7" + numeroRolFormateado;
        return codigoRolCompleto;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new PanelImgFondo("/recursos/fondoFormularios.png");
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtCodigoRol = new javax.swing.JTextField();
        txtDescripcionRol = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        btnCrearRol = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        spnNumeroRol = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Nuevo rol");

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(780, 500));

        jLabel2.setFont(new java.awt.Font("Microsoft JhengHei", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 204));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Nuevo Rol");

        txtCodigoRol.setEditable(false);
        txtCodigoRol.setBackground(new java.awt.Color(237, 243, 251));

        txtDescripcionRol.setBackground(new java.awt.Color(237, 243, 251));

        btnCrearRol.setBackground(new java.awt.Color(58, 181, 235));
        btnCrearRol.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        btnCrearRol.setForeground(new java.awt.Color(255, 255, 255));
        btnCrearRol.setText("Crear Rol");
        btnCrearRol.setBorderPainted(false);
        btnCrearRol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearRolActionPerformed(evt);
            }
        });

        btnCancelar.setBackground(new java.awt.Color(234, 242, 251));
        btnCancelar.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(67, 113, 177));
        btnCancelar.setText("Cancelar");
        btnCancelar.setBorderPainted(false);
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 779, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(220, 220, 220)
                        .addComponent(btnCrearRol, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txtCodigoRol, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(spnNumeroRol, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtDescripcionRol))
                .addGap(123, 123, 123))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel2)
                .addGap(12, 12, 12)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(92, 92, 92)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCodigoRol, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spnNumeroRol, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addComponent(txtDescripcionRol, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(165, 165, 165)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCrearRol, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(108, 108, 108)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(112, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(79, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCrearRolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearRolActionPerformed
        // Numero del codigo
        String numeroRolFormateado = obtenerNumeroRolFormateado();
        String codigoRolCompleto = obtenerCodigoRolCompleto();

        System.out.println("Numero del rol: " + numeroRolFormateado);
        System.out.println("Codigo completo del rol: " + codigoRolCompleto);

        // Descripcion
        String descripcionRol = txtDescripcionRol.getText().trim();

        if (codigoRolCompleto.isEmpty() || descripcionRol.isEmpty()) {
            JOptionPane.showMessageDialog(
                    this,
                    "Debes rellenar todos los campos del formulario",
                    "Datos incompletos",
                    JOptionPane.WARNING_MESSAGE
            );
        } else {
            String mensajeError = gestionRolControlador.crearRol(codigoRolCompleto, descripcionRol);

            if (mensajeError == null) {
                JOptionPane.showMessageDialog(this, "Nuevo rol registrado con exito", "Insercion realizada", JOptionPane.INFORMATION_MESSAGE);

                // Limpiamos los campos
                txtDescripcionRol.setText("");
                spnNumeroRol.setValue(1);

                // Mostramos la tabla actualizada
                gestionRol.mostrarTabla();

            } else {
                JOptionPane.showMessageDialog(this, mensajeError, "Error al crear rol", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnCrearRolActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        int respuesta = JOptionPane.showConfirmDialog(this, "¿Deseas cancelar la operación? Los cambios no se guardarán.", "Cancelar operación", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
        if (respuesta == JOptionPane.YES_OPTION) {
            dispose();
        }
    }//GEN-LAST:event_btnCancelarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnCrearRol;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSpinner spnNumeroRol;
    private javax.swing.JTextField txtCodigoRol;
    private javax.swing.JTextField txtDescripcionRol;
    // End of variables declaration//GEN-END:variables
}
